export const categories = [
    { id: 1, name: "Electronics", image: "/src/photos/electronics.jpg" },
    { id: 2, name: "Fashion", image: "/src/photos/fashion.jpg" },
    { id: 3, name: "Home & Kitchen", image: "/src/photos/home_kitchen.jpg" },
    { id: 4, name: "Sports", image: "/src/photos/sports.jpg" },
    { id: 5, name: "Books", image: "/src/photos/books.jpg" },
    { id: 6, name: "Toys & Games", image: "/src/photos/toys_games.jpg" },
    { id: 7, name: "Beauty & Personal Care", image: "/src/photos/beauty.jpg" },
    { id: 8, name: "Automotive", image: "/src/photos/automotive.jpg" },
    { id: 9, name: "Grocery", image: "/src/photos/grocery.jpg" },
    { id: 10, name: "Furniture", image: "/src/photos/furniture.jpg" }
];

export const products = [
    // Electronics
    { id: 1, name: "Smartphone", price: 699.99, color: "Black", category: "Electronics", image: "https://via.placeholder.com/300x200?text=Smartphone" },
    { id: 2, name: "Laptop", price: 999.99, color: "Silver", category: "Electronics", image: "https://via.placeholder.com/300x200?text=Laptop" },
    { id: 3, name: "Smartwatch", price: 199.99, color: "Blue", category: "Electronics", image: "https://via.placeholder.com/300x200?text=Smartwatch" },
    { id: 4, name: "Headphones", price: 79.99, color: "Red", category: "Electronics", image: "https://via.placeholder.com/300x200?text=Headphones" },
    { id: 5, name: "Gaming Console", price: 499.99, color: "White", category: "Electronics", image: "https://via.placeholder.com/300x200?text=Gaming+Console" },
    { id: 6, name: "Tablet", price: 349.99, color: "Gray", category: "Electronics", image: "https://via.placeholder.com/300x200?text=Tablet" },
    { id: 7, name: "Camera", price: 599.99, color: "Black", category: "Electronics", image: "https://via.placeholder.com/300x200?text=Camera" },
    { id: 8, name: "Speaker", price: 129.99, color: "Blue", category: "Electronics", image: "https://via.placeholder.com/300x200?text=Speaker" },
    { id: 9, name: "Monitor", price: 249.99, color: "Black", category: "Electronics", image: "https://via.placeholder.com/300x200?text=Monitor" },
    { id: 10, name: "Keyboard", price: 49.99, color: "White", category: "Electronics", image: "https://via.placeholder.com/300x200?text=Keyboard" },

    // Fashion
    { id: 11, name: "Men's T-Shirt", price: 19.99, color: "Black", category: "Fashion", image: "https://via.placeholder.com/300x200?text=Men's+T-Shirt" },
    { id: 12, name: "Women's Dress", price: 49.99, color: "Red", category: "Fashion", image: "https://via.placeholder.com/300x200?text=Women's+Dress" },
    { id: 13, name: "Sneakers", price: 89.99, color: "White", category: "Fashion", image: "https://via.placeholder.com/300x200?text=Sneakers" },
    { id: 14, name: "Jeans", price: 39.99, color: "Blue", category: "Fashion", image: "https://via.placeholder.com/300x200?text=Jeans" },
    { id: 15, name: "Jacket", price: 99.99, color: "Black", category: "Fashion", image: "https://via.placeholder.com/300x200?text=Jacket" },
    { id: 16, name: "Handbag", price: 59.99, color: "Brown", category: "Fashion", image: "https://via.placeholder.com/300x200?text=Handbag" },
    { id: 17, name: "Sunglasses", price: 29.99, color: "Black", category: "Fashion", image: "https://via.placeholder.com/300x200?text=Sunglasses" },
    { id: 18, name: "Watch", price: 149.99, color: "Silver", category: "Fashion", image: "https://via.placeholder.com/300x200?text=Watch" },
    { id: 19, name: "Scarf", price: 14.99, color: "Gray", category: "Fashion", image: "https://via.placeholder.com/300x200?text=Scarf" },
    { id: 20, name: "Hat", price: 24.99, color: "Black", category: "Fashion", image: "https://via.placeholder.com/300x200?text=Hat" },

    // Home & Kitchen
    { id: 21, name: "Blender", price: 49.99, color: "Black", category: "Home & Kitchen", image: "https://via.placeholder.com/300x200?text=Blender" },
    { id: 22, name: "Coffee Maker", price: 79.99, color: "Silver", category: "Home & Kitchen", image: "https://via.placeholder.com/300x200?text=Coffee+Maker" },
    { id: 23, name: "Cookware Set", price: 129.99, color: "Gray", category: "Home & Kitchen", image: "https://via.placeholder.com/300x200?text=Cookware+Set" },
    { id: 24, name: "Air Fryer", price: 99.99, color: "White", category: "Home & Kitchen", image: "https://via.placeholder.com/300x200?text=Air+Fryer" },
    { id: 25, name: "Vacuum Cleaner", price: 149.99, color: "Blue", category: "Home & Kitchen", image: "https://via.placeholder.com/300x200?text=Vacuum+Cleaner" },
    { id: 26, name: "Toaster", price: 29.99, color: "Black", category: "Home & Kitchen", image: "https://via.placeholder.com/300x200?text=Toaster" },
    { id: 27, name: "Dinnerware Set", price: 59.99, color: "White", category: "Home & Kitchen", image: "https://via.placeholder.com/300x200?text=Dinnerware+Set" },
    { id: 28, name: "Food Processor", price: 89.99, color: "Silver", category: "Home & Kitchen", image: "https://via.placeholder.com/300x200?text=Food+Processor" },
    { id: 29, name: "Microwave", price: 119.99, color: "Black", category: "Home & Kitchen", image: "https://via.placeholder.com/300x200?text=Microwave" },
    { id: 30, name: "Rice Cooker", price: 39.99, color: "White", category: "Home & Kitchen", image: "https://via.placeholder.com/300x200?text=Rice+Cooker" },

    // Sports
    { id: 31, name: "Running Shoes", price: 89.99, color: "Black", category: "Sports", image: "https://via.placeholder.com/300x200?text=Running+Shoes" },
    { id: 32, name: "Yoga Mat", price: 24.99, color: "Purple", category: "Sports", image: "https://via.placeholder.com/300x200?text=Yoga+Mat" },
    { id: 33, name: "Dumbbell Set", price: 69.99, color: "Black", category: "Sports", image: "https://via.placeholder.com/300x200?text=Dumbbell+Set" },
    { id: 34, name: "Treadmill", price: 499.99, color: "Gray", category: "Sports", image: "https://via.placeholder.com/300x200?text=Treadmill" },
    { id: 35, name: "Bicycle", price: 299.99, color: "Red", category: "Sports", image: "https://via.placeholder.com/300x200?text=Bicycle" },
    { id: 36, name: "Basketball", price: 19.99, color: "Orange", category: "Sports", image: "https://via.placeholder.com/300x200?text=Basketball" },
    { id: 37, name: "Tennis Racket", price: 49.99, color: "Black", category: "Sports", image: "https://via.placeholder.com/300x200?text=Tennis+Racket" },
    { id: 38, name: "Gym Gloves", price: 14.99, color: "Black", category: "Sports", image: "https://via.placeholder.com/300x200?text=Gym+Gloves" },
    { id: 39, name: "Jump Rope", price: 9.99, color: "Blue", category: "Sports", image: "https://via.placeholder.com/300x200?text=Jump+Rope" },
    { id: 40, name: "Resistance Bands", price: 19.99, color: "Multicolor", category: "Sports", image: "https://via.placeholder.com/300x200?text=Resistance+Bands" },

    // Books
    { id: 41, name: "Novel", price: 14.99, color: "N/A", category: "Books", image: "https://via.placeholder.com/300x200?text=Novel" },
    { id: 42, name: "Cookbook", price: 24.99, color: "N/A", category: "Books", image: "https://via.placeholder.com/300x200?text=Cookbook" },
    { id: 43, name: "Self-Help Book", price: 19.99, color: "N/A", category: "Books", image: "https://via.placeholder.com/300x200?text=Self-Help+Book" },
    { id: 44, name: "Children's Book", price: 9.99, color: "N/A", category: "Books", image: "https://via.placeholder.com/300x200?text=Children's+Book" },
    { id: 45, name: "Science Fiction", price: 12.99, color: "N/A", category: "Books", image: "https://via.placeholder.com/300x200?text=Science+Fiction" },
    { id: 46, name: "Biography", price: 17.99, color: "N/A", category: "Books", image: "https://via.placeholder.com/300x200?text=Biography" },
    { id: 47, name: "History Book", price: 22.99, color: "N/A", category: "Books", image: "https://via.placeholder.com/300x200?text=History+Book" },
    { id: 48, name: "Poetry Book", price: 11.99, color: "N/A", category: "Books", image: "https://via.placeholder.com/300x200?text=Poetry+Book" },
    { id: 49, name: "Art Book", price: 29.99, color: "N/A", category: "Books", image: "https://via.placeholder.com/300x200?text=Art+Book" },
    { id: 50, name: "Comic Book", price: 7.99, color: "N/A", category: "Books", image: "https://via.placeholder.com/300x200?text=Comic+Book" },

    // Toys & Games
    { id: 51, name: "LEGO Set", price: 49.99, color: "Multicolor", category: "Toys & Games", image: "https://via.placeholder.com/300x200?text=LEGO+Set" },
    { id: 52, name: "Board Game", price: 29.99, color: "Multicolor", category: "Toys & Games", image: "https://via.placeholder.com/300x200?text=Board+Game" },
    { id: 53, name: "Action Figure", price: 19.99, color: "Multicolor", category: "Toys & Games", image: "https://via.placeholder.com/300x200?text=Action+Figure" },
    { id: 54, name: "Puzzle", price: 14.99, color: "Multicolor", category: "Toys & Games", image: "https://via.placeholder.com/300x200?text=Puzzle" },
    { id: 55, name: "Doll", price: 24.99, color: "Pink", category: "Toys & Games", image: "https://via.placeholder.com/300x200?text=Doll" },
    { id: 56, name: "Remote Control Car", price: 39.99, color: "Red", category: "Toys & Games", image: "https://via.placeholder.com/300x200?text=Remote+Control+Car" },
    { id: 57, name: "Building Blocks", price: 19.99, color: "Multicolor", category: "Toys & Games", image: "https://via.placeholder.com/300x200?text=Building+Blocks" },
    { id: 58, name: "Stuffed Animal", price: 12.99, color: "Brown", category: "Toys & Games", image: "https://via.placeholder.com/300x200?text=Stuffed+Animal" },
    { id: 59, name: "Toy Train Set", price: 59.99, color: "Multicolor", category: "Toys & Games", image: "https://via.placeholder.com/300x200?text=Toy+Train+Set" },
    { id: 60, name: "Video Game", price: 49.99, color: "N/A", category: "Toys & Games", image: "https://via.placeholder.com/300x200?text=Video+Game" },

    // Beauty & Personal Care
    { id: 61, name: "Shampoo", price: 9.99, color: "N/A", category: "Beauty & Personal Care", image: "https://via.placeholder.com/300x200?text=Shampoo" },
    { id: 62, name: "Conditioner", price: 9.99, color: "N/A", category: "Beauty & Personal Care", image: "https://via.placeholder.com/300x200?text=Conditioner" },
    { id: 63, name: "Face Cream", price: 19.99, color: "N/A", category: "Beauty & Personal Care", image: "https://via.placeholder.com/300x200?text=Face+Cream" },
    { id: 64, name: "Lipstick", price: 14.99, color: "Red", category: "Beauty & Personal Care", image: "https://via.placeholder.com/300x200?text=Lipstick" },
    { id: 65, name: "Perfume", price: 49.99, color: "N/A", category: "Beauty & Personal Care", image: "https://via.placeholder.com/300x200?text=Perfume" },
    { id: 66, name: "Hair Dryer", price: 39.99, color: "Pink", category: "Beauty & Personal Care", image: "https://via.placeholder.com/300x200?text=Hair+Dryer" },
    { id: 67, name: "Electric Shaver", price: 59.99, color: "Black", category: "Beauty & Personal Care", image: "https://via.placeholder.com/300x200?text=Electric+Shaver" },
    { id: 68, name: "Sunscreen", price: 12.99, color: "N/A", category: "Beauty & Personal Care", image: "https://via.placeholder.com/300x200?text=Sunscreen" },
    { id: 69, name: "Makeup Kit", price: 29.99, color: "N/A", category: "Beauty & Personal Care", image: "https://via.placeholder.com/300x200?text=Makeup+Kit" },
    { id: 70, name: "Nail Polish", price: 7.99, color: "Red", category: "Beauty & Personal Care", image: "https://via.placeholder.com/300x200?text=Nail+Polish" },

    { id: 71, name: "Car Wax", price: 15.99, color: "Clear", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Car+Wax" },
    { id: 72, name: "Tire Cleaner", price: 12.99, color: "Black", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Tire+Cleaner" },
    { id: 73, name: "Windshield Wipers", price: 9.99, color: "Clear", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Windshield+Wipers" },
    { id: 74, name: "Seat Covers", price: 24.99, color: "Black", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Seat+Covers" },
    { id: 75, name: "Car Battery", price: 59.99, color: "Black", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Car+Battery" },
    { id: 76, name: "Car Vacuum Cleaner", price: 39.99, color: "Red", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Car+Vacuum+Cleaner" },
    { id: 77, name: "Air Freshener", price: 5.99, color: "Blue", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Air+Freshener" },
    { id: 78, name: "Car Charger", price: 8.99, color: "Silver", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Car+Charger" },
    { id: 79, name: "Engine Oil", price: 13.99, color: "Yellow", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Engine+Oil" },
    { id: 80, name: "Brake Pads", price: 29.99, color: "Black", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Brake+Pads" },

    { id: 81, name: "Car Wax", price: 15.99, color: "Clear", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Car+Wax" },
    { id: 82, name: "Tire Cleaner", price: 12.99, color: "Black", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Tire+Cleaner" },
    { id: 83, name: "Windshield Wipers", price: 9.99, color: "Clear", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Windshield+Wipers" },
    { id: 84, name: "Seat Covers", price: 24.99, color: "Black", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Seat+Covers" },
    { id: 85, name: "Car Battery", price: 59.99, color: "Black", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Car+Battery" },
    { id: 86, name: "Car Vacuum Cleaner", price: 39.99, color: "Red", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Car+Vacuum+Cleaner" },
    { id: 87, name: "Air Freshener", price: 5.99, color: "Blue", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Air+Freshener" },
    { id: 88, name: "Car Charger", price: 8.99, color: "Silver", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Car+Charger" },
    { id: 89, name: "Engine Oil", price: 13.99, color: "Yellow", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Engine+Oil" },
    { id: 90, name: "Brake Pads", price: 29.99, color: "Black", category: "Automotive", image: "https://via.placeholder.com/300x200?text=Brake+Pads" },

    { id: 91, name: "Bread", price: 1.99, color: "Brown", category: "Grocery", image: "https://via.placeholder.com/300x200?text=Bread" },
    { id: 92, name: "Milk", price: 2.49, color: "White", category: "Grocery", image: "https://via.placeholder.com/300x200?text=Milk" },
    { id: 93, name: "Eggs", price: 3.99, color: "White", category: "Grocery", image: "https://via.placeholder.com/300x200?text=Eggs" },
    { id: 94, name: "Apples", price: 5.99, color: "Red", category: "Grocery", image: "https://via.placeholder.com/300x200?text=Apples" },
    { id: 95, name: "Bananas", price: 2.99, color: "Yellow", category: "Grocery", image: "https://via.placeholder.com/300x200?text=Bananas" },
    { id: 96, name: "Tomatoes", price: 3.49, color: "Red", category: "Grocery", image: "https://via.placeholder.com/300x200?text=Tomatoes" },
    { id: 97, name: "Carrots", price: 2.49, color: "Orange", category: "Grocery", image: "https://via.placeholder.com/300x200?text=Carrots" },
    { id: 98, name: "Potatoes", price: 4.99, color: "Brown", category: "Grocery", image: "https://via.placeholder.com/300x200?text=Potatoes" },
    { id: 99, name: "Onions", price: 1.99, color: "Yellow", category: "Grocery", image: "https://via.placeholder.com/300x200?text=Onions" },
    { id: 100, name: "Lettuce", price: 3.99, color: "Green", category: "Grocery", image: "https://via.placeholder.com/300x200?text=Lettuce" },

    { id: 101, name: "Sofa", price: 299.99, color: "Gray", category: "Furniture", image: "https://via.placeholder.com/300x200?text=Sofa" },
    { id: 102, name: "Dining Table", price: 199.99, color: "Wood", category: "Furniture", image: "https://via.placeholder.com/300x200?text=Dining+Table" },
    { id: 103, name: "Chair", price: 49.99, color: "Black", category: "Furniture", image: "https://via.placeholder.com/300x200?text=Chair" },
    { id: 104, name: "Coffee Table", price: 129.99, color: "Wood", category: "Furniture", image: "https://via.placeholder.com/300x200?text=Coffee+Table" },
    { id: 105, name: "Bookshelf", price: 89.99, color: "Black", category: "Furniture", image: "https://via.placeholder.com/300x200?text=Bookshelf" },
    { id: 106, name: "Wardrobe", price: 249.99, color: "Brown", category: "Furniture", image: "https://via.placeholder.com/300x200?text=Wardrobe" },
    { id: 107, name: "Nightstand", price: 69.99, color: "White", category: "Furniture", image: "https://via.placeholder.com/300x200?text=Nightstand" },
    { id: 108, name: "TV Stand", price: 159.99, color: "Black", category: "Furniture", image: "https://via.placeholder.com/300x200?text=TV+Stand" },
    { id: 109, name: "Recliner", price: 399.99, color: "Brown", category: "Furniture", image: "https://via.placeholder.com/300x200?text=Recliner" },
    { id: 110, name: "Desk", price: 119.99, color: "Wood", category: "Furniture", image: "https://via.placeholder.com/300x200?text=Desk" }
];
export const notificationData = [
    { id: 1, title: "New Items Arrived." },
    { id: 2, title: "Delivered Product." },
    { id: 3, title: "New Items Arrived." },
    { id: 4, title: "Payment Pending, Please Pay." },
];